---
- name: Add repository from PPA and install its signing key.
  apt_repository:
    repo: 'ppa:duplicity-team/ppa'
    update_cache: true

- name: Install duplicity.
  apt: "name=duplicity state=latest"

- name: Install duply.
  copy:
    src: duply
    dest: /usr/local/bin/duply
    mode: 0755
